### ISSUE TITLE
NetGain replying to Ping with OpCode.Binary

### ISSUE THREAD

**Issue by InFaMoUsZero** [StackExchange/NetGain#13]
Inside of 

> NetGain/StackExchange.NetGain/WebSockets/WebSocketsProcessor_RFC6455_13.cs

Is it intended for the ping to be handled with `pong.OpCode = WebSocketsFrame.OpCodes.Binary; `

I was getting client disconnects because ping was not being responded to with a pong.

I've changed it to `OpCodes.Pong;` and it works as expected. Is this a bug or is there a apart of the RFC6455 standard that I'm missing?

**Comment by mgravell** [comment]
On 9 December 2016 at 11:07, Lee Fitzpatrick <notifications@github.com>
wrote:

> pong.OpCode = WebSocketsFrame.OpCodes.Binary;
>

Huh,  yeah  that  looks   like a typo indeed. Thanks.



-- 
Regards,

Marc
