### ISSUE TITLE
A binary array sent to NetGain isn't received into the .Value property of the received message

### ISSUE THREAD

**Issue by paulmrozowski** [StackExchange/NetGain#7]
I'm not sure if I doing something wrong or this just isn't working. Inside of the Console app included in the source, I added this code:

 ```C#
               Console.WriteLine("Server running");

               // Send ourselves a message
               byte[] data = new byte[2] { 0x10, 0x20 };
               using (var client = new TcpClient())
                {
                    client.ProtocolFactory = WebSocketClientFactory.Default;
                    client.Open(new IPEndPoint(IPAddress.Loopback, 6002));
                    var response = client.ExecuteSync(data);
                }

When I run it and set a breakpoint on the received event, nothing is in the Value property. I am supposed to do something else here?

**Comment by mgravell** [comment]
Ahem... I guess we dropped a ball there; that is fixed in the code above; here's my test rig for it:

            using(var server = new TcpServer())
            {
                server.ProtocolFactory = WebSocketsSelectorProcessor.Default;
                server.ConnectionTimeoutSeconds = 60;
                server.Received += msg =>
                {
                    var conn = (WebSocketConnection)msg.Connection;
                    var data = (byte[])msg.Value;
                    Console.WriteLine("[server] {0}", BitConverter.ToString(data));
                    Array.Reverse(data);
                    msg.Connection.Send(msg.Context, data);
                };
                server.Start("abc", endpoint);
                Console.WriteLine("Server running");

                using (var client = new TcpClient())
                {
                    byte[] data = new byte[2] { 0x10, 0x20 };
                    client.ProtocolFactory = WebSocketClientFactory.Default;
                    client.Open(endpoint);
                    var response = (byte[])client.ExecuteSync(data, 1000000);
                    Console.WriteLine("[client] {0}", BitConverter.ToString(response));
                }
            }

**Comment by mgravell** [comment]
Note: you'll need to update from source, or we need to update/deploy any public packages etc. Sorry about the inconvenience.

**Comment by paulmrozowski** [comment]
Great, will do. Thanks.

**Comment by DoraemonYu** [comment]
Hello. 
I'm facing the same problem and then I found the page.

BTW, the packages in nuget is still the version published **2016-01-26**, also effect as 
`PM > Install-Package StackExchange.NetGain`
So the fix above wasn't include now.

Counld you update/deploy again to nuget , or create a Build directory to github for saving the newest  Bulided DLL,convenient for developments.

Thanks so much.
